config/routes.rb
FinalProject::Application.routes.draw do

  devise_for :users
  # :controllers => { :registrations => 'users/registrations' }
  # careful! call devise_for once only and do it before resource users!

  root to: "home#index" # req for devise config

  resources :users #, except: [:index ]

  #nested routes
  # , except: [:index, :edit, :update]
  resources :photos, except: [:index] do
    resources :memories
  end

  get   'dashboard',        :to => "users#dashboard"
  get   'journey',          :to => "users#journey"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
      user ||= User.new # guest user (not logged in)
      if user.admin?
        can :manage, :all
      else
        can :read, :all

        # cannot DESTROY or UPDATE other USERS!
        can [:new, :create, :show], User
        can [:edit, :update, :destroy], User do |current_user|
          current_user.id == user.id
        end

        can [:new, :create, :show], Photo
        can [:edit, :update, :destroy], Photo do |photo|
          photo.user == user
        end

        can [:new, :create, :show], Memory
        can [:edit, :update, :destroy], Memory do |memory|
          memory.user == user
        end
      end
  end

end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :address, :latitude, :longitude, :created_at

  geocoded_by :address
  after_validation :geocode

  belongs_to :photo
end

app/models/memory.rb
class Memory < ActiveRecord::Base
  attr_accessible :text, :track, :created_at

  belongs_to :user
  belongs_to :photo
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  attr_accessible :title, :image, :remote_image_url, :user_id, :created_at, :memories_attributes, :location_attributes

  # acts_as_voteable
  # acts_as_taggable

  ### ASSOCIATIONS
  belongs_to :user
  has_many :memories
  has_one :location

  ### NESTED MODEL FORMS
  accepts_nested_attributes_for :memories
  accepts_nested_attributes_for :location

  # accepts_nested_attributes_for :location

  ### CARRIERWAVE
  mount_uploader :image, ImageUploader


  def as_json(options = {})
    super options.merge(:methods => [:location, :title, :image], :only => [:id, :latitude, :longitude])
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :first_name, :last_name, :username, :favourite_location, :about_me, :email, :password, :password_confirmation, :admin, :remember_me, :confirmed_at, :avatar

  # attr_accessible :title, :body

  ### CARRIERWAVE
  mount_uploader :avatar, AvatarUploader

  ### VALIDATIONS
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :username, presence: true


  ### ASSOCIATIONS
  has_many :photos
  # has_one :location, through: :photo
  # has_many :memories, through: :photo

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def after_sign_in_path_for(resource)
    dashboard_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    if current_user
      redirect_to dashboard_url
    else
      @user = User.new
    end
  end

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

  def new
    @photo = Photo.find(params[:photo_id])
    @location = Location.new
  end

  def create
    @location = Location.new(params[:location])
    @location.photo_id = params[:photo_id]
    @location.user_id = current_user.id
    if @location.save
      redirect_to @location.photo
    else
      flash[:alert] = "Memory NOT created!"
      render :new
    end
  end

  def show
    @location = Location.find(params[:id])
  end

  def edit
    @location = Location.find(params[:id])
  end


  def update
    # memory = Memory.find(params[:id])
    location.update_attributes(params[:location])
    redirect_to(location)
  end


  def destroy
    location = Location.find(params[:id])
    location.delete
    # redirect_to(memory.photo), notice: "Memory successfully DELETED!!!"
  end

end

app/controllers/memories_controller.rb
class MemoriesController < ApplicationController


  def index
    @memories = Memory.all
  end


  def new
    @photo = Photo.find(params[:photo_id])
    @memory = Memory.new
    authorize! :new, @memory
  end


  def create
    @memory = Memory.new(params[:memory])
    @memory.photo_id = params[:photo_id]
    @memory.user_id = current_user.id
    if @memory.save
      redirect_to @memory.photo, notice: "Memory created successfully!"
    else
      flash[:alert] = "Memory NOT created!"
      render :new
    end
    authorize!(:create, @memory || Memory)
  end


  def show
    @memory = Memory.find(params[:id])
  end


  def edit
    @memory = Memory.find(params[:id])
  end


  def update
    # memory = Memory.find(params[:id])
    memory.update_attributes(params[:memory])
    redirect_to(memory)
    authorize! :update, memory
  end


  def destroy
    memory = Memory.find(params[:id])
    memory.delete
    authorize! :destroy, memory
    # redirect_to(memory.photo), notice: "Memory successfully DELETED!!!"
  end


end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController


  def index
    @photos = Photo.all
  end


  def new
    @photo = Photo.new
    @photo.memories.build
    @photo.build_location
    authorize! :new, @photo
  end


  def create
    photo_hash = params[:photo]
    location_hash = photo_hash.delete("location")

    @photo = Photo.new photo_hash
    @photo.user_id = current_user.id
    if @photo.save
      session[:photo_id] = @photo.id
      redirect_to dashboard_path
    else
      render :new
    end
    authorize!(:create, @photo || Photo)
  end


  def show
    @photo = Photo.find(params[:id])
    authorize! :show, @photo

  end


  def edit
    @photo = Photo.find(params[:id])
    authorize! :edit, @photo
  end


  def update
    photo_hash = params[:photo]
    location_hash = photo_hash.delete("location")

    photo = Photo.find(params[:id])
    photo.update_attributes(photo_hash)

    if photo.location.nil?
      location = Location.new(location_hash)
      location.save
      photo.location = location
    end

    authorize! :update, photo
    redirect_to dashboard_path
  end


  def destroy
    photo = Photo.find(params[:id])
    authorize! :destroy, photo
    photo.delete
    redirect_to dashboard_path
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # @photos = @user.photos
  def dashboard
    if current_user
      @photos = current_user.photos
    else
      redirect_to :new_user_session
    end
  end

  def index
    @users = User.all
    @users -= [current_user]
  end

  def show
    @user = User.find(params[:id])
    authorize! :show, @user
  end

  def edit
    @user = User.find(params[:id])
    authorize! :edit, @user
  end

  def destroy
    user = User.find(params[:id])
    authorize! :destroy, user
    user.delete
    redirect_to users_path
  end

  def journey
    @photos = current_user.photos.includes(:location)
    @locations
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.haml
!!!
%html
  %head
    %title Final Project

  %body
  %ul.slider
    %li
      %img.carousel{src: "/assets/photography/london_underground.jpg"}/
    %li
      %img.carousel{src: "/assets/photography/london_town2.jpg"}/
    %li
      %img.carousel{src: "/assets/photography/william_gig.jpg"}/
    %li
      %img.carousel{src: "/assets/photography/london_town3.jpg"}/
    %li
      %img.carousel{src: "/assets/photography/long_exposure.jpg"}/
    %li
      %img.carousel{src: "/assets/photography/long_exposure2.jpg"}/
    %li
      %img.carousel{src: "/assets/photography/girls_girls_girls.jpg"}/
    %li
      %img.carousel{src: "/assets/photography/football.jpg"}/
    %li
      %img.carousel{src: "/assets/photography/cinema.jpg"}/
    %li
      %img.carousel{src: "/assets/photography/ladies_innit.jpg"}/
    %li
      %img.carousel{src: "/assets/photography/room_view.jpg"}/
    %li
      %img.carousel{src: "/assets/photography/westway_william.jpg"}/
    %li
      %img.carousel{src: "/assets/photography/piccadilly.jpg"}/
    %li
      %img.carousel{src: "/assets/photography/maxd_tube.jpg"}/
    %li
      %img.carousel{src: "/assets/photography/piccadilly_tube.jpg"}/

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Final Project
    = stylesheet_link_tag    "application", :media => "all"
    / %script{src: "//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"}
    %script{src: "https://maps.googleapis.com/maps/api/js?key=AIzaSyCyjPnob22nV_GJZJqiiuUGR-DvSaPq5vI&sensor=false&libraries=places"}

    %link{href: 'http://fonts.googleapis.com/css?family=Open+Sans:400,300,700,600', rel: 'stylesheet', type: 'text/css'}/

    = javascript_include_tag "application"
    = csrf_meta_tags

    %body
      %nav.nav
        = link_to root_url do
          %img.logo{src: "/assets/neeeha.jpg"}

        - flash.each do |name, msg|
          = content_tag :div, msg, :id => "flash_#{name}"
        - if user_signed_in?
          %logged_in
            %ul.left
              .link.dashboard.link-style
                = link_to 'DASHBOARD', dashboard_path
              .link.journey.link-style
                = link_to 'JOURNEY', journey_path
            %ul.right
              =link_to current_user do
                .link.avatar
                  = image_tag current_user.avatar, {:class => 'nav-avatar'}
                .link.logout
                  = link_to 'LOGOUT',  destroy_user_session_path, method: :delete
        - else
          %ul
          .nav-links
            .link.sign_up
              = link_to 'SIGN-UP', new_user_registration_path, {:class => 'sign-up-link'}
            .link.sign_in
              = link_to 'LOGIN', new_user_session_path

    = yield

app/views/memories/_form.html.haml
= form_for(@memory) do |f|

  = f.label :text
  = f.text_field :text
  %br

  / = f.label :track
  / = f.audio_field :track
  / %br

  = f.submit class: "btn btn-primary"

app/views/memories/edit.html.haml
%h2 Edit #{@memory.text}

= render 'form'

app/views/memories/index.html.haml
%h3 Memories

- @memories.each do |memory|
  %h3= memory.text
  = link_to "Delete", memory_path(memory), method: :delete
  |\
  = link_to "Edit", edit_memory_path(memory)

app/views/memories/new.html.haml
%h2 Add a new Memory

= form_for([@photo, @memory]) do |f|
  .field
    = f.label :text
    = f.text_field :text
    = hidden_field_tag :photo_id, @photo.id
    %br/

    = f.submit class: "btn btn-primary"


%p
/ = link_to "Back to Photo", @photo

app/views/memories/show.html.haml
%p
  = @memory.text

app/views/photos/_form.html.haml
#photos-form
  = form_for(@photo) do |f|
    .photo-text
      = f.label :title
      = f.text_field :title
      %br/

    .photo-image
      = f.label :image
      = f.file_field :image
      %br/

    .photo-memory
      = f.fields_for :memories do |f|
        = f.label :memory
        = f.text_field :text
      %br/

    .photo-location
      = f.fields_for :location do |f|
        = f.label :address
        = f.text_field :address
      %br
    .photo-button
      = f.submit class: "btn btn-primary"

app/views/photos/edit.html.haml
%h2 Edit

= render "form"


%p
  = link_to "Back to Dashboard", dashboard_path

app/views/photos/index.html.haml
%h1 Photos

- @photos.each do |photo|
  %h3= photo.title
  %h3= image_tag photo.image
  / = link_to "Delete", photo_path(photo), method: :delete
  / |\
  / = link_to "Edit", edit_photo_path(photo)

app/views/photos/new.html.haml
#photos-new-page
  %h2.photos-new Add a Photograph

  = render "form"

  %p
  = link_to "Back to Dashboard", dashboard_path

app/views/photos/show.html.haml
- if current_user.admin == true
  %h2= @photo.title
  = image_tag @photo.image
  %br/
  = link_to "Delete Photo", photo_path(photo), method: :delete
- else
  %h2= @photo.title
  = image_tag @photo.image

/ - if current_user.admin == true
/   - @photos.each do |photo|
/     %h2= @photo.title
/     = image_tag @photo.image
/     %br/
/     = link_to "Delete Photo", photo_path(photo), method: :delete
/ - else
/   - @photos.each do |photo|
/     %h2= @photo.title
/     = image_tag @photo.image



/ To show MEMORIES or not to show MEMORIES... that is my question?!?

/ %h5 Memories

/ - @photo.memories.each do |memory|
/   .photo-memory
/   %p
/     = memory.text
/     \::
/     = memory.user.username

app/views/users/_form.html.haml
/ = form_for(@user) do |f|
/   .field
/     = f.label :first_name
/     = f.text_field :first_name
/     %br/

/   .field
/     = f.label :last_name
/     = f.file_field :last_name
/     %br/

/   .field
/     = f.label :username
/     = f.text_field :username
/     %br/

/     = f.submit class: "btn btn-primary"

app/views/users/dashboard.html.haml
%body.dash
  .photos-dash.col-md-12
    - if @photos.present?
      - @photos.each do |photo|
        .photo-dash.col-md-4
          .title
            = photo.title
          .picture
            = link_to photo.image_url, class: 'image' do
              = image_tag photo.image_url(:thumb), class: "col-md-12"
            .clearfix
          .links
            = link_to "Delete", photo_path(photo), method: :delete
            |
            = link_to "Edit", edit_photo_path(photo)
          .memories
            %ul
              - photo.memories.each do |memory|
                %li= memory.text
          .location
            / = photo.location.address unless photo.location.nil?
            = "Location: #{photo.location.address}" unless photo.location.nil?
      .col-md-4.add_photo_box= link_to "+", new_photo_path
      .clearfix

    - else
      .col-md-4.add_photo_box= link_to "+", new_photo_path
      .clearfix

app/views/users/index.html.haml
%h1 Users

- if current_user.admin == true
  .photos-users-index
    - @users.each do |user|
      .photo-users-index
        .username
          %h3= link_to user.username, user_path(user)
        .user-avatar
          = image_tag user.avatar
          %br/
        .user-link-delete
          = link_to "Delete User", user_path(user), method: :delete
- else
  .photos-users-index
    - @users.each do |user|
      / %h3= link_to user.username, user_path(user)
      .photo-users-index
        .username
          %h3= user.username
        .user-avatar
          =  image_tag user.avatar



  / =link_to user.journey PAGES when they click on AVATAR picture

app/views/users/journey.html.haml
!!!
%html

%body.jour
  .container-jour
    %form#places_form
      .row{role: "search"}
    %input#autocomplete
      .form{placholder: "search", type: "text"}

    #map-canvas

    :javascript
      window.photos = #{@photos.to_json}

app/views/users/new.html.haml
%h1 New user

= render 'form'

- if current_user.admin == true
  = link_to 'Back to all Users', users_path
-else
  = link_to 'My Dashboard', dashboard_path

app/views/users/show.html.haml
%body
  .container
    .users-show
      .user-show-username
        %h1= @user.username

      .row
        .user-show-left.col-md-4
          .user-show-name
            %p
              %b= @user.first_name
              %b= @user.last_name
          .user-show-avatar
            = image_tag @user.avatar

        .user-show-right.col-md-4
          .user-show-location
            %p
              %b Favourite Location:
              = @user.favourite_location
          .user-show-aboutme
            %p
              %b About Me:
              = @user.about_me

      - if current_user # if current user LOGGED IN, then show...
        .user-profile-link
          = link_to "Update Profile", edit_user_registration_path